version: "3.8"

services:
  # Load Balancer HAProxy
  haproxy:
    image: haproxy:2.8
    container_name: haproxy_loadbalancer
    ports:
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      # certs for certificate
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - study-space

  study-space:
    build:
      context: ../ # root of the project
      dockerfile: docker/Dockerfile
    expose:
      - "8080" # port for docker
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/study_space_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-toor}
      JWT_SECRET: ${JWT_SECRET_KEY:-una_clave_secreta_muy_larga_por_defecto_para_desarrollo}

      MAIL_PASSWORD: ${MAIL_PASSWORD}
      NORMAL_PASSWORD: ${NORMAL_PASSWORD}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}

      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadminpassword}
      MINIO_BUCKET: studyspace-images
    deploy:
      replicas: 3 # 3 containersof the same app
    depends_on:
      - mysql
      - minio

  # Database MySQL
  mysql:
    image: mysql:8.0
    container_name: study_space_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-toor}
      MYSQL_DATABASE: study_space_db
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: study_space_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadminpassword}
    command: server /data --console-address ":9001"
    expose:
      - "9000" # Puerto API interno (no sale al host)
      - "9001" # Puerto Consola interno
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc
    container_name: study_space_minio_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to start...';
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword; do
        sleep 2;
      done;
      echo 'MinIO done. Configuring bucket...';
      /usr/bin/mc mb myminio/studyspace-images --ignore-existing;
      /usr/bin/mc anonymous set download myminio/studyspace-images;
      exit 0;
      "

volumes:
  mysql_data:
  minio_data:
